# Generated by Django 3.1.7 on 2022-08-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0011_proposal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='modify_date',
        ),
    ]
